/* You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t. */

 class Solution {
    public char findTheDifference(String s, String t) {
        char result = 0;

        for (char c : s.toCharArray())
         {
            result ^= c; 
        }
        
        for (char c : t.toCharArray())
         {
            result ^= c;  
        }

        return result; 
    }
}
